@extends('base.backend')

@section('title')
Campaign Contacts
@stop

@section('content-title')
Contacts for {{ $campaign->title }}
@stop

@section('inner-content')
<p class="small">These are the members who will receive texts generated by this campaign</p>
<ul class="nav nav-pills">
    <li class="active"><a href="{{ action('CampaignController@getContacts', [$campaign->id]) }}" class="tooltips" data-toggle="tooltip" title="Contacts Already Added to this campaign">Campaign Contacts</a></li>
    <li><a href="{{ action('CampaignController@getAddContacts', [$campaign->id]) }}" class="tooltips" data-toggle="tooltip" title="Add more Contacts to this campaign">Add</a></li>
</ul>



@if($contacts->isEmpty())
<p class="alert alert-info">Whoops! Looks like this campaign has no contacts</p>
@else 


<form method="post" action="{{ action('CampaignController@postContacts', [$campaign->id]) }}">
    {!! Form::token() !!}
    <button id="select-all" class="btn btn-xs btn-info">Select all</button>
    <button id="deselect-all" class="btn btn-xs btn-default">Deselect All</button>
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Number</th>
            </tr>
        </thead>
        <tbody>
            @foreach($contacts as $c)
            <tr>
                <td><input type="checkbox" name="remove[]" value="{{$c->id}}" /></td>
                <td>{{$c->getFullName() }}</td>
                <td>{{ $c->phone }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <button class="btn btn-danger" type="submit">Remove</button>
</form>
<br />
@endif
{!! $contacts->render() !!}
<br />
<p>
    <a href="{{ action('CampaignController@getReview', [$campaign->id]) }}" class="btn btn-default pull-right">Next &rarr;</a>
    <a href="{{ action('CampaignController@getAnswers', [$campaign->id]) }}" class="btn btn-default">&larr; Back</a>    
</p>
@stop
